language: php

php:
  - 7.1
  - 7.2
  - 7.3

notifications:
  email: false
  slack:
    secure: ZQGUEu+N9otf3DhMJ1Qmn/oY0kSRylNRgqRcXcrBTs12ZUBPI7k4MVsNQCXAn7+mFSccPxhjnAjdj/bzISc0ngwEYqMiNX3xDimuFP7BwUnQIjsftDSDAQnt7kZy29eVd9kojPiwcYOxT8hPKEk8znXIvGgbfbY3ie9zT8CT/VY=

install:
  - composer selfupdate
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
